"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Building2, Check, Home, LockKeyhole, Mail, Phone, User } from "lucide-react";
import type { Role } from "@/lib/tenant-data";

export default function SignupForm() {
  const router = useRouter(); const [role, setRole] = useState<Role>("landlord"); const [loading, setLoading] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); localStorage.setItem("rentify-role", role); window.setTimeout(() => router.push("/dashboard"), 500); }
  return <main className="auth-shell min-h-dvh bg-[#f2f6f3] p-4 sm:p-7"><div className="mx-auto grid min-h-[calc(100dvh-2rem)] max-w-6xl overflow-hidden rounded-[32px] border border-[#dce6e1] bg-white shadow-[0_24px_70px_rgba(21,65,47,.12)] lg:grid-cols-[.82fr_1.18fr]">
    <section className="relative hidden overflow-hidden bg-[#173d31] p-12 text-white lg:flex lg:flex-col"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-white text-[#126b49]"><Building2 /></span><div><b className="text-xl">RENTIFY</b><p className="text-xs text-white/65">Renting made simple</p></div></div><div className="my-auto"><h1 className="text-4xl font-bold leading-tight">A better rental experience starts here.</h1><div className="mt-8 space-y-4">{["Simple rent and bill tracking","Tenant and flat management","Direct landlord communication"].map((text) => <p key={text} className="flex items-center gap-3 text-sm text-white/75"><span className="grid size-6 place-items-center rounded-full bg-emerald-400/15 text-emerald-300"><Check size={14} /></span>{text}</p>)}</div></div></section>
    <section className="flex items-center justify-center p-5 sm:p-10 lg:p-12"><div className="w-full max-w-xl"><div className="mb-7 lg:hidden"><span className="flex items-center gap-2 text-xl font-bold text-[#126b49]"><Building2 /> RENTIFY</span></div><p className="text-sm font-bold text-[#168159]">Create your account</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em] text-[#15271f]">Get started with RENTIFY</h2><p className="mt-2 text-sm text-[#71847d]">Select how you will use the platform.</p>
      <div className="mt-6 grid grid-cols-2 gap-2 rounded-2xl bg-[#eef3f0] p-1.5">{(["landlord", "tenant"] as const).map((item) => <button key={item} onClick={() => setRole(item)} className={`flex h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold capitalize transition ${role === item ? "bg-white text-[#126b49] shadow-sm" : "text-[#71847d]"}`}>{item === "landlord" ? <Building2 size={17} /> : <Home size={17} />}{item}</button>)}</div>
      <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><SignupField icon={<User />} label="Full name" name="name" placeholder="Your full name" /><SignupField icon={<Phone />} label="Phone number" name="phone" placeholder="01XXXXXXXXX" /><SignupField icon={<Mail />} label="Email address" name="email" type="email" placeholder="you@example.com" /><SignupField icon={<LockKeyhole />} label="Password" name="password" type="password" placeholder="Minimum 6 characters" />{role === "landlord" ? <SignupField icon={<Building2 />} label="Property name" name="property" placeholder="e.g. Green View House" /> : <SignupField icon={<Home />} label="Flat or invite code" name="flat" placeholder="Optional" />}<SignupField icon={<LockKeyhole />} label="Confirm password" name="confirmPassword" type="password" placeholder="Repeat password" /><label className="flex items-start gap-2 text-xs text-[#71847d] sm:col-span-2"><input required type="checkbox" className="mt-0.5 accent-[#168159]" /> I agree to RENTIFY’s terms and privacy policy.</label><button disabled={loading} className="h-12 rounded-xl bg-[#168159] font-bold text-white shadow-[0_8px_20px_rgba(22,129,89,.22)] sm:col-span-2">{loading ? "Creating account..." : `Create ${role} account`}</button></form>
      <p className="mt-6 text-center text-sm text-[#71847d]">Already registered? <Link href="/signin" className="font-bold text-[#168159]">Sign in</Link></p></div></section>
  </div></main>;
}

function SignupField({ icon, label, name, placeholder, type = "text" }: { icon: React.ReactNode; label: string; name: string; placeholder: string; type?: string }) { return <label className="block text-sm font-bold text-[#294139]">{label}<div className="relative mt-2"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#82928b] [&>svg]:size-[18px]">{icon}</span><input required name={name} type={type} className="h-12 w-full rounded-xl border border-[#dce5e1] bg-[#fbfcfb] pl-11 pr-4 text-sm font-normal outline-none focus:border-[#168159]" placeholder={placeholder} /></div></label>; }
