"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Building2, Eye, EyeOff, Home, LockKeyhole, Mail } from "lucide-react";
import type { Role } from "@/lib/tenant-data";

export default function SigninForm() {
  const router = useRouter();
  const [role, setRole] = useState<Role>("landlord");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); localStorage.setItem("rentify-role", role); window.setTimeout(() => router.push("/dashboard"), 450); }
  return <main className="auth-shell min-h-dvh bg-[#f2f6f3] p-4 sm:p-7"><div className="mx-auto grid min-h-[calc(100dvh-2rem)] max-w-6xl overflow-hidden rounded-[32px] border border-[#dce6e1] bg-white shadow-[0_24px_70px_rgba(21,65,47,.12)] lg:grid-cols-[.92fr_1.08fr]">
    <section className="relative hidden overflow-hidden bg-[#126b49] p-12 text-white lg:flex lg:flex-col"><div className="absolute -right-24 -top-24 size-72 rounded-full bg-white/10" /><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-white text-[#126b49]"><Building2 /></span><div><b className="text-xl">RENTIFY</b><p className="text-xs text-white/65">Renting made simple</p></div></div><div className="relative my-auto"><p className="text-sm font-bold uppercase tracking-[.18em] text-emerald-200">One place. Every property.</p><h1 className="mt-5 max-w-md text-4xl font-bold leading-tight">Manage homes and relationships with confidence.</h1><p className="mt-5 max-w-md leading-7 text-white/68">Rent, tenants, flats, bills and conversations—organized for landlords and residents.</p></div><p className="text-xs text-white/45">Secure access for every RENTIFY account</p></section>
    <section className="flex items-center justify-center p-5 sm:p-10 lg:p-14"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><span className="flex items-center gap-2 text-xl font-bold text-[#126b49]"><Building2 /> RENTIFY</span></div><p className="text-sm font-bold text-[#168159]">Welcome back</p><h2 className="mt-2 text-3xl font-bold tracking-[-.04em] text-[#15271f]">Sign in to your account</h2><p className="mt-2 text-sm text-[#71847d]">Choose your account type and continue.</p>
      <div className="mt-7 grid grid-cols-2 gap-2 rounded-2xl bg-[#eef3f0] p-1.5">{(["landlord", "tenant"] as const).map((item) => <button key={item} onClick={() => setRole(item)} className={`flex h-12 items-center justify-center gap-2 rounded-xl text-sm font-bold capitalize transition ${role === item ? "bg-white text-[#126b49] shadow-sm" : "text-[#71847d]"}`}>{item === "landlord" ? <Building2 size={17} /> : <Home size={17} />}{item}</button>)}</div>
      <form onSubmit={submit} className="mt-7 space-y-5"><AuthField icon={<Mail />} label="Email address" name="email" type="email" placeholder="you@example.com" /><label className="block text-sm font-bold text-[#294139]">Password<div className="relative mt-2"><LockKeyhole className="absolute left-3.5 top-1/2 size-[18px] -translate-y-1/2 text-[#82928b]" /><input required name="password" type={showPassword ? "text" : "password"} className="h-12 w-full rounded-xl border border-[#dce5e1] bg-[#fbfcfb] px-11 text-sm outline-none focus:border-[#168159]" placeholder="••••••••" /><button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-[#82928b]">{showPassword ? <EyeOff size={18} /> : <Eye size={18} />}</button></div></label><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2 text-[#71847d]"><input type="checkbox" className="accent-[#168159]" /> Remember me</label><button type="button" className="font-bold text-[#168159]">Forgot password?</button></div><button disabled={loading} className="h-12 w-full rounded-xl bg-[#168159] font-bold text-white shadow-[0_8px_20px_rgba(22,129,89,.22)] transition hover:bg-[#106d4a] disabled:opacity-70">{loading ? "Signing in..." : `Sign in as ${role}`}</button></form>
      <p className="mt-7 text-center text-sm text-[#71847d]">New to RENTIFY? <Link href="/signup" className="font-bold text-[#168159]">Create an account</Link></p></div></section>
  </div></main>;
}

function AuthField({ icon, label, name, type, placeholder }: { icon: React.ReactNode; label: string; name: string; type: string; placeholder: string }) { return <label className="block text-sm font-bold text-[#294139]">{label}<div className="relative mt-2"><span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-[#82928b] [&>svg]:size-[18px]">{icon}</span><input required name={name} type={type} className="h-12 w-full rounded-xl border border-[#dce5e1] bg-[#fbfcfb] pl-11 pr-4 text-sm outline-none focus:border-[#168159]" placeholder={placeholder} /></div></label>; }
